### ISSUE TITLE
Shouldn't ${MCRT} param be called ${M68K_CRT} or something?

### ISSUE THREAD

**Issue by tehKaiN** [AmigaPorts/AmigaCMakeCrossToolchains#7]
As in title. I know it's trivial but consider it as a low priority pedantic issue. There is also wider problem with naming convention:

- CPU and FPU parameters start with `M68K_`
- all other parameters start with `TOOLCHAIN_` (`TOOLCHAIN_PREFIX`, )
- there is also combination of both: `M68K_TOOLCHAIN_PATH`

I think this should be unified. I vote for `M68K_` because it's shorter. ;)

**Comment by MBeijer** [comment]
yeah, make a PR for it. :)
